server {
    listen 80;
    server_name fazo.ch-khana.ru;
    root /usr/share/nginx/html;
    index index.html;
    charset utf-8;

    location /api/ {
        proxy_pass         http://api:3000;
        proxy_http_version 1.1;
        proxy_set_header   Host $host;
        proxy_set_header   X-Real-IP $remote_addr;
        client_max_body_size 20m;
    }

    location /uploads/ {
        alias   /usr/share/nginx/html/uploads/;
        expires 30d;
        add_header Cache-Control "public, no-transform";
    }

    location / {
        try_files $uri $uri/ /index.html;
    }

    location = /favicon.ico { log_not_found off; access_log off; }

    location ~* \.(css|js|png|jpg|jpeg|gif|svg|ico|woff2?)$ {
        expires 7d;
        add_header Cache-Control "public, no-transform";
    }

    location ~ /\. { deny all; }
}
